title:              Jyaquinas
# email:
description:        Personal Blog Space
author:             jyaquinas
baseurl:            "/"
url:                "https://jyaquinas.github.io"

# Social Profiles
# twitter_username:
github_username:    jyaquinas
# facebook_username:
# instagram_username:
# linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-220919399-1 # out your google-analytics code

collections:
  collection1:
    output: true
    permalink: /collection1/:name

# Build settings
markdown:           kramdown
paginate:           10
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

highlighter: rouge
kramdown:
  input: GFM
